name: create zip when main branch is pushed
on:
  push:
    #branches:
    #  - master
    paths:
      - "src/**"
      - ".github/workflows/deploy-s3.yaml"
      - "package.json"

defaults:
  run:
    shell: bash

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: myGitHubActions
      - run: |
          aws sts get-caller-identity
